FROM python:3.12-slim

RUN apt-get update \
    && apt-get install -y tzdata \
    && rm -rf /var/lib/apt/lists/*
	
WORKDIR /app

COPY planningAdguard.py confPlanning.yml ./

RUN pip install requests pyyaml

CMD ["python", "-u",  "planningAdguard.py"]
